version: "3.3"

services:
  database:
    image: "postgres:11-alpine"
    restart: "always"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres-data:/var/lib/postgresql/data"
